<?php

$data = 
[
    [
        "name" => "Fajitas di pollo",
        "description" => "Striscioline di petto di pollo marinate in spezie messicane e cucinate con cipolle e peperoni",
        "price"=>17.00,
        "visible"=>true,
        "available"=>true,
        "image"=>"https://www.sempliceveloce.it/wordpress/wp-content/uploads/2012/03/ricetta-fajitas-messicane-con-pollo-e-peperoni-640x420.jpg",
    ],
    [
        "name" => "Margherita",
        "description" => "Pomodori pelati, spolverata di formaggio grattugiato e fior di latte d'Agerola",
        "price"=>10.00,
        "visible"=>true,
        "available"=>true,
        "image"=>"https://www.finedininglovers.it/sites/g/files/xknfdk1106/files/styles/recipes_1200_800_fallback/public/fdl_content_import_it/margherita-50kalo.jpg?itok=v9nHxNMS",
    ],
    [
        "name" => "Chicken Burger",
        "description" => "Pollo alla piastra, insalata, pomodoro. salsa ranch e pane",
        "price"=>8.50,
        "visible"=>true,
        "available"=>true,
        "image"=>"https://simply-delicious-food.com/wp-content/uploads/2022/06/Grilled-chicken-burgers2.jpg",
    ],
    [
        "name" => "Ravioli di carne al vapore",
        "description" => "Maiale, erba cipollina, cipolotto fresco, cavolo cappuccio",
        "price"=>3.20,
        "visible"=>true,
        "available"=>true,
        "image"=>"https://www.tavolartegusto.it/ricetta/ravioli-al-vapore-cinesi/",
    ],
    [
        "name" => "Lanzhou Lamian ",
        "description" => "Il Lamian con il tradizionale brodo di manzo cotto per 4 ore con 19 spezie diverse, con la salsa piccante aromatizzata di nostra produzione ed il prezzemolo cinese",
        "price"=>11.00,
        "visible"=>true,
        "available"=>true,
        "image"=>"https://staticfanpage.akamaized.net/wp-content/uploads/sites/21/2016/03/ramen-ricetta.jpg",
    ],
    [
        "name" => "Cacio e pepe",
        "description" => "pecorino romano D.O.P. e pepe nero TGEB indiano macinato al momento",
        "price"=>9.80,
        "visible"=>true,
        "available"=>true,
        "image"=>"https://www.italianstylecooking.net/wp-content/uploads/2019/02/Spaghetti-cacio-e-pepe-isc-1200x900.jpg",
    ],
    [
        "name" => "Spaghetti Fiori di zucca e alici",
        "description" => "Spaghetti con fiori di zucca e alici con aglio, olio e peperoncino",
        "price"=>10.50,
        "visible"=>true,
        "available"=>true,
        "image"=>"https://www.mangiaconme.it/wp-content/uploads/2020/11/Spaghetti-con-alici-e-fiori-di-zucca.jpg",
    ],
    [
        "name" => "Pizza Capricciosa",
        "description" => "Pizza con pomodoro, mozzarella, prosciutto cotto, funghi e carciofi",
        "price"=>6.50,
        "visible"=>true,
        "available"=>true,
        "image"=>"https://i0.wp.com/www.piccolericette.net/piccolericette/wp-content/uploads/2017/12/3240_Pizza.jpg?resize=895%2C616&ssl=1",
    ],
    [
        "name" => "Pizza Patate e Salsiccia",
        "description" => "Pizza con patate e salsiccia",
        "price"=>7.50,
        "visible"=>true,
        "available"=>true,
        "image"=>"https://i0.wp.com/www.ibocconighiottidilolly.it/wp-content/uploads/2021/04/IMG_6379-compressed-scaled.jpg?resize=750%2C500&ssl=1",
    ],
    [
        "name" => "Pizza alla Diavola",
        "description" => "Pizza con pomodoro e salame piccante",
        "price"=>7.20,
        "visible"=>true,
        "available"=>true,
        "image"=>"https://www.negroni.com/sites/negroni.com/files/styles/scale__1440_x_1440_/public/pizza_rustica.jpg?itok=Lbp_jtZW",
    ],
];